---
language: ruby
rvm:
- 2.2.5

install:
  - bundle install
  - sudo pip install pytest

script:
  - jekyll build
  - htmlproofer ./_site --allow-hash-href --internal-domains netsysops.github.io --http-status-ignore 999
  - cp _site-validation/site-validation.md _pages
  - jekyll build
  - pytest
